### ISSUE TITLE
Turn signal & blind spot indicators

### ISSUE THREAD

**Issue by Donfyffe** [neokii/op4#2]
Neokii thanks for this fork, I really appreciate your work. Can you put back the turn signal indicators and blind spot monitor in openpilot paint.cc. Thanks

**Comment by oricalworks** [comment]
Yes please

**Comment by oricalworks** [comment]
Here is an example I was trying all morning to get this working with no progress. Line 422
https://github.com/xx979xx/openpilot/blob/Xps_Community_Release/selfdrive/ui/paint.cc

**Comment by oricalworks** [comment]
Check my latest commits here I have got it working test and merge
https://github.com/oricalworks/openpilot/tree/hkg_085_KG_dev/selfdrive/ui

**Comment by oricalworks** [comment]
It's very cool the turn signals are animated

**Comment by oricalworks** [comment]
All commits starting with this one https://github.com/oricalworks/openpilot/commit/b53201da90dec91e488de4d025d9ed5b86e7754b and ending with this one 
https://github.com/oricalworks/openpilot/commit/c02d1f9e00ded98b2df3f5ac5358507b73ade37e

**Comment by Donfyffe** [comment]
Fixed, thank you oricalworks, this one is the best.
