### ISSUE TITLE
Neokii!!!! Open Street Maps Integration Done!!!!, please add to SCC smoother. Slow for curves using map data works! but not speed limit adjust.

### ISSUE THREAD

**Issue by oricalworks** [neokii/op4#44]
Open Street Maps Integration Done, please add to SCC smoother. Slow for curves using map data works! but not speed limit
UI looks very good with signs and everything!
Please check it out I know you can make it even better!
https://github.com/Circuit-Pro/openpilot/tree/OSM-DEV - Works!
https://github.com/Circuit-Pro/openpilot/tree/SPAS-OSM - Works!
https://github.com/move-fast/openpilot/tree/release_0.8.7 - Sources!

**Comment by neokii** [comment]
Hello.
Sorry, OMP's road speed limit is not accurate, so I don't plan to use it.

**Comment by oricalworks** [comment]
How can I have scc smoother update to speed limit?
Which line sets speed?

**Comment by oricalworks** [comment]
What in scc_smoother.py sets cruise set speed?
Is it v_cruise_kph?

**Comment by oricalworks** [comment]
Or is it set_speed

**Comment by oricalworks** [comment]
Thanks I’m advance I really appreciate your replies!
